package utils;

import java.lang.reflect.*;
import java.util.ArrayList;

/**
 * @author tlvlp
 */
public class ModuleExecuter {
    /**
     * Launches a class.mehtod from a string input using reflection.
     * @requires A valid problemID in String format
     *           problemID = classname in the problems package = ID in Rosalind url = ID in input txt file name
     * @requires An ArrayList with the parsed contents of the input File - passing on to the problem module
     * @return   The ArrayList with the results generated by the problem module - passing it back to the main Rosalind class.
     * @param problemID
     * @param inList
     * @throws Exception
     */
    public static ArrayList<String> launch(String problemID, ArrayList<String> inList) throws Exception {
        ArrayList<String> outList = new ArrayList<>();
        
        String aClass = "problems." + problemID;   //the package name is hardcoded 
        String aMethod = "solve";               //this is the method for all the problems classes
        
        Class[] parameterTypes = new Class[] {java.util.ArrayList.class};
        Object[] arguments = new Object[] {inList};
        
        Class thisClass = Class.forName(aClass);
        // get an instance
        Object iClass = thisClass.newInstance();
        // get the method
        Method thisMethod = thisClass.getDeclaredMethod(aMethod, parameterTypes);
        // call the method
        return (ArrayList<String>) thisMethod.invoke(iClass, arguments);
    }
}  
